apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb
  namespace: argocd
spec:
  project: default
  source:
    chart: cockroachdb
    repoURL: https://charts.cockroachdb.com/
    targetRevision: 10.0.8
    helm:
      releaseName: cockroachdb
      valueFiles:
        - ../cockroachdb/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cockroachdb
  syncPolicy:
    automated:
        prune: true
        allowEmpty: true
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
