apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  project: default
  source:
    path: harbor
    repoURL: git@github.com:b-reich/home_k8s.git
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true