apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
  namespace: argocd
spec:
  project: default
  source:
    chart: wiki
    repoURL: https://charts.js.wiki
    targetRevision: 2.2.20
    helm:
      releaseName: wiki
      valueFiles:
        - /wikijs/values.yml
        #- ../wikijs/values.yml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wikijs
  syncPolicy:
    automated:
        prune: true
        allowEmpty: true
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
