apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cockroachdb
      repoURL: https://charts.cockroachdb.com/
      targetRevision: 10.0.8
      helm:
        releaseName: cockroachdb
        valueFiles:
        - $values/cockroachdb/values.yml
    - repoURL: git@github.com:b-reich/home_k8s.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cockroachdb
  syncPolicy:
    automated:
        prune: true
        allowEmpty: true
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
